services:
  # portfolio_builder_api:
  #   build:
  #     context: .
  #     dockerfile: portfolio_builder_server/Dockerfile
  #   ports:
  #     - "5000:80"
  #   volumes:
  #     - ./portfolio_builder_server/uploads:/app/uploads
  #   depends_on:
  #     - sql
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data: